In [1]:

import os
import torch as torch
import pickle

market_name = 'NASDAQ'

dataset_path = 'dataset/' + market_name

with open(os.path.join(dataset_path, "eod_data.pkl"), "rb") as f:
    eod_data = pickle.load(f)
with open(os.path.join(dataset_path, "mask_data.pkl"), "rb") as f:
    mask_data = pickle.load(f)
with open(os.path.join(dataset_path, "gt_data.pkl"), "rb") as f:
    gt_data = pickle.load(f)
with open(os.path.join(dataset_path, "price_data.pkl"), "rb") as f:
    price_data = pickle.load(f)

/home/zjx/anaconda3/envs/qlib-master/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
print(price_data)
print(price_data.shape)

[[0.275333 0.271219 0.272316 ... 0.951735 0.962841 0.976964]
 [0.248031 0.252493 0.253806 ... 0.952756 0.951444 0.937008]
 [0.445018 0.439414 0.427177 ... 0.958976 0.960735 0.961019]
 ...
 [0.42501  0.425589 0.437766 ... 0.964824 0.975454 0.984345]
 [0.30288  0.303243 0.308567 ... 0.972289 0.985358 0.99758 ]
 [0.471014 0.51256  0.518841 ... 0.508454 0.51087  0.512077]]
(1026, 1245)


In [7]:
import os
import pickle
import numpy as np

market_name = 'NASDAQ'
dataset_path = 'dataset/' + market_name

# 加载eod_data
with open(os.path.join(dataset_path, "price_data.pkl"), "rb") as f:
    eod_data = pickle.load(f)

# 打印eod_data的形状
print(f"eod_data.shape: {eod_data.shape}")

# 检查eod_data中是否存在大于1的值
has_values_greater_than_1 = np.any(eod_data > 1)
max_value = np.max(eod_data)

print(f"eod_data中是否存在大于1的值: {has_values_greater_than_1}")
print(f"eod_data中的最大值: {max_value}")

# 如果存在大于1的值，打印这些值的数量和位置
if has_values_greater_than_1:
    greater_than_1_count = np.sum(eod_data > 1)
    greater_than_1_indices = np.where(eod_data > 1)
    print(f"大于1的值的数量: {greater_than_1_count}")
    print(f"大于1的值的位置示例(前10个): {list(zip(*[i[:10] for i in greater_than_1_indices]))}") 

eod_data.shape: (1026, 1245)
eod_data中是否存在大于1的值: True
eod_data中的最大值: 1.100000023841858
大于1的值的数量: 1728
大于1的值的位置示例(前10个): [(8, 1231), (8, 1232), (8, 1233), (8, 1234), (8, 1235), (8, 1236), (8, 1237), (8, 1238), (8, 1239), (8, 1240)]


In [8]:
print(mask_data)
print(mask_data.shape)
print(gt_data)
print(gt_data.shape)
print(price_data)
print(price_data.shape)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
(1026, 1245)
[[ 0.         -0.01494191  0.00404479 ...  0.01878863  0.01166917
   0.01466807]
 [ 0.          0.01798964  0.00520015 ... -0.03328856 -0.00137708
  -0.01517267]
 [ 0.         -0.01259275 -0.02784841 ... -0.00371412  0.0018343
   0.00029556]
 ...
 [ 0.          0.00136232  0.02861209 ... -0.01886759  0.0110175
   0.00911478]
 [ 0.          0.00119857  0.0175568  ... -0.00297884  0.01344145
   0.01240361]
 [ 0.          0.08820549  0.01225421 ...  0.01937087  0.00475157
   0.00236262]]
(1026, 1245)
[[0.275333 0.271219 0.272316 ... 0.951735 0.962841 0.976964]
 [0.248031 0.252493 0.253806 ... 0.952756 0.951444 0.937008]
 [0.445018 0.439414 0.427177 ... 0.958976 0.960735 0.961019]
 ...
 [0.42501  0.425589 0.437766 ... 0.964824 0.975454 0.984345]
 [0.30288  0.303243 0.308567 ... 0.972289 0.985358 0.99758 ]
 [0.471014 0.51256

In [10]:
# 统计mask_data中0和1的数量
zeros_count = (mask_data == 0).sum()
ones_count = (mask_data == 1).sum()

print(f"mask_data中0的数量: {zeros_count}")
print(f"mask_data中1的数量: {ones_count}")
print(f"总数据点数量: {mask_data.size}")
print(f"0的占比: {zeros_count/mask_data.size*100:.2f}%")
print(f"1的占比: {ones_count/mask_data.size*100:.2f}%")

mask_data中0的数量: 1728
mask_data中1的数量: 1275642
总数据点数量: 1277370
0的占比: 0.14%
1的占比: 99.86%


In [11]:
import numpy as np


# 2. 在您的项目中的实际使用示例
# 以SP500数据为例
sp500_data = np.load('dataset/SP500/SP500.npy')
print(f"SP500数据形状: {sp500_data.shape}")

# 选择部分数据（这里是从第915列开始的所有数据）
data = sp500_data[:, 915:, :]
# 提取价格数据（最后一列）
print(data)

SP500数据形状: (474, 2526, 5)
[[[0.13653708 0.13713569 0.13633367 0.03608551 0.13700788]
  [0.13662301 0.1375307  0.13678475 0.02230004 0.13761357]
  [0.1349902  0.13610524 0.13522329 0.02172257 0.13631565]
  ...
  [0.69567908 0.70331629 0.69386514 0.07277307 0.70045864]
  [0.69329    0.69546774 0.66365937 0.05412213 0.67353124]
  [0.66415731 0.68320536 0.65770844 0.06917312 0.68095528]]

 [[0.40426041 0.39552864 0.40436553 0.09072705 0.40175422]
  [0.40402108 0.39711227 0.40654342 0.097402   0.40242158]
  [0.4017712  0.39450395 0.40475268 0.16760683 0.40170654]
  ...
  [0.87343232 0.85756869 0.87532671 0.08900596 0.87348654]
  [0.87745337 0.87452258 0.88713584 0.07099012 0.89341214]
  [0.89640977 0.87498837 0.89352434 0.10202212 0.89055205]]

 [[0.43928987 0.43503576 0.43233263 0.05139081 0.43785674]
  [0.43760186 0.44005072 0.43743404 0.0315252  0.43541062]
  [0.42974389 0.427715   0.42482702 0.05358237 0.42679091]
  ...
  [0.68102444 0.67615867 0.67292135 0.02451036 0.67990681]
  [0.678